### ISSUE TITLE
Three examples terminate with uncaught exception

### ISSUE THREAD

**Issue by roversch** [luczeng/HoughRectangle#10]
The following executables:
- main_hough_rectangle 
- windowed_hough
- hough_transform

all terminate with uncaught exception `std::domain_error`. 

I'm on Apple LLVM 8.1.0.

**Comment by luczeng** [comment]
This is probably due to using JPEG images. The library only supports JPEG as of now. 

Note that the algorithm expects edge detected images. You have some python scripts in utils that you can use to generate data. Otherwise, there is a test image called "shape_and_color_edge.png" in "img" folder.

Documentation will be changed in the next commit.
